######################
# book (meta) info

title: Azrieli Students On Software Modeling and Architecture
author: 
  name: robi-y

github:
  url: "https://github.com/jce-il/ASOSMA"

#url: "https://github.com/jce-il/ASOSMA"
#baseurl: /ASOSMA

#highlighter: pygments
relative_permalinks: false

timezone: UTC+2
#include: [chapters/]
exclude: ['Makefile']

# Server settings
#host: 0.0.0.0

########
# more settings
baseurl: "/" 

markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true # Auto-generate ID's for headings


#include: [jekyll/]


